INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('제목1', '내용1', 'user 1', NOW(), NOW())
INSERT INTO comments (article_id, author, content, created_at) VALUES ('1','user 4', '댓글1', NOW())
INSERT INTO comments (article_id, author, content, created_at) VALUES ('1','user 5', '댓글2', NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('제목2', '내용2', 'user 2', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('제목3', '내용3', 'user 3', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('제목4', '내용4', '23', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('제목5', '내용5', '2r3', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('제목6', '내용6', '35', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('제목7', '내용7', 'fe', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('제목8', '내용8', 'ewr', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('제목9', '내용9', 'wt', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('제목10', '내용10', 'rt', NOW(), NOW())
INSERT INTO article (title, content, author, created_at, updated_at) VALUES ('제목11', '내용11', 'eere', NOW(), NOW())